
import Link from 'next/link';
import { PageHeader } from '@/components/page-header';
import { PageFooter } from '@/components/page-footer';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col items-center p-4 sm:p-8 font-body">
      <PageHeader />
      <main className="w-full max-w-3xl flex-grow prose dark:prose-invert">
        <Button variant="ghost" asChild className="mb-6">
          <Link href="/">
            <ArrowLeft className="mr-2 h-4 w-4" /> Back to Home
          </Link>
        </Button>
        <h1 className="font-headline text-3xl sm:text-4xl text-primary mb-6">Terms of Service</h1>
        <p>Last updated: August 1, 2024</p>

        <h2 className="font-headline text-2xl mt-6 mb-3">1. Acceptance of Terms</h2>
        <p>By accessing and using PhotoVerse (the "Service"), you accept and agree to be bound by the terms and provision of this agreement. Any participation in this Service will constitute acceptance of this agreement.</p>

        <h2 className="font-headline text-2xl mt-6 mb-3">2. Description of Service</h2>
        <p>PhotoVerse is an AI-powered tool that transforms user-provided images and/or text descriptions into poems. The Service uses artificial intelligence models to generate content based on your inputs.</p>

        <h2 className="font-headline text-2xl mt-6 mb-3">3. User Conduct and Responsibilities</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>You are solely responsible for the images and text you upload or input into the Service ("User Content").</li>
          <li>You agree not to use the Service to upload or create any content that is unlawful, harmful, threatening, abusive, defamatory, obscene, or otherwise objectionable.</li>
          <li>You represent and warrant that you own or have the necessary licenses and rights to use the content you provide.</li>
          <li>You understand that the poems and images generated are created by AI and may not always be accurate, appropriate, or meet your expectations. The output is for creative and entertainment purposes.</li>
        </ul>

        <h2 className="font-headline text-2xl mt-6 mb-3">4. Intellectual Property</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>Your Content:</strong> You retain full ownership of the content you provide to the Service. We do not claim any rights to your images or text descriptions.</li>
          <li><strong>Generated Content:</strong> You are free to use the poems and images generated by the Service for personal and commercial purposes, subject to the terms of the underlying AI models. As the user, you are responsible for ensuring your use of the generated content is lawful and does not infringe on the rights of any third party.</li>
          <li><strong>Our Service:</strong> All rights, title, and interest in and to the Service itself (excluding User Content and generated content) are and will remain the exclusive property of PhotoVerse and its licensors.</li>
        </ul>

        <h2 className="font-headline text-2xl mt-6 mb-3">5. Disclaimer of Warranties</h2>
        <p>The Service is provided "as is" and "as available" without any warranties of any kind, express or implied, including but not limited to the implied warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that the Service will be uninterrupted, timely, secure, or error-free.</p>
        
        <h2 className="font-headline text-2xl mt-6 mb-3">6. Limitation of Liability</h2>
        <p>In no event shall PhotoVerse, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any content obtained from the Service; and (iii) any use of the content you generate, whether based on warranty, contract, tort (including negligence) or any other legal theory.</p>

        <h2 className="font-headline text-2xl mt-6 mb-3">7. Modifications to Terms</h2>
        <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms of Service on this page and updating the "Last updated" date. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms.</p>

        <h2 className="font-headline text-2xl mt-6 mb-3">8. Governing Law</h2>
        <p>These Terms shall be governed and construed in accordance with the laws of [Your Jurisdiction, e.g., State of California, USA], without regard to its conflict of law provisions.</p>
        
        <h2 className="font-headline text-2xl mt-6 mb-3">9. Contact Us</h2>
        <p>If you have any questions about these Terms, please <Link href="/contact-us" className="text-primary hover:underline">contact us</Link>.</p>

        <p className="mt-8 text-sm text-muted-foreground">
          This is a sample Terms of Service. You should consult with a legal professional to ensure it meets your specific needs and complies with all applicable laws and regulations. Remember to replace "[Your Jurisdiction]" with the appropriate legal jurisdiction.
        </p>
      </main>
      <PageFooter />
    </div>
  );
}
